
class TRADE_TYPE:
	BUY_BELOW_AT_MARKET = 'BUY_BELOW_AT_MARKET'
	SELL_ABOVE_AT_MARKET = 'SELL_ABOVE_AT_MARKET'
	SELL_BELOW_AT_MARKET = 'SELL_BELOW_AT_MARKET'
	TRAILING_STOP_LOSS = 'TRAILING_STOP_LOSS'
	ALERT_ABOVE = 'ALERT_ABOVE'
	ALERT_BELOW = 'ALERT_BELOW'
	ALL = [BUY_BELOW_AT_MARKET, SELL_ABOVE_AT_MARKET, SELL_BELOW_AT_MARKET, TRAILING_STOP_LOSS, ALERT_ABOVE, ALERT_BELOW]

kRunInterval = 10

kMaxRunInterval = 60

